#!/usr/bin/env ruby
# frozen_string_literal: true

# Converts the canonical nested Kotlin dictionaries into flat Swift catalogs.
# The generated file is committed so the iOS app has no runtime dependency on
# the Android source tree. Run this script whenever a Kotlin dictionary changes.

require "json"

ROOT = File.expand_path("../..", __dir__)
SOURCE_DIR = File.join(ROOT, "kotlin/app/src/main/java/br/com/tscode/checking/i18n/dictionaries")
OUTPUT = File.join(ROOT, "ios/Checking/Domain/I18n/LocalizationCatalogs.generated.swift")
LANGUAGES = %w[pt en zh ms id tl].freeze

Token = Struct.new(:kind, :value)

class KotlinDictionaryParser
  def initialize(source)
    @tokens = tokenize(source)
    map_starts = @tokens.each_index.select do |index|
      token = @tokens[index]
      token.kind == :identifier && token.value == "d"
    end
    # The first `d` declares the helper itself; the second starts the dictionary.
    @index = map_starts.fetch(1)
  end

  def parse
    parse_map
  end

  private

  def tokenize(source)
    tokens = []
    index = 0
    while index < source.length
      if source[index, 2] == "//"
        index = source.index("\n", index + 2) || source.length
        next
      elsif source[index, 2] == "/*"
        finish = source.index("*/", index + 2)
        index = finish ? finish + 2 : source.length
        next
      end
      case source[index]
      when '"'
        finish = index + 1
        escaped = false
        while finish < source.length
          character = source[finish]
          if !escaped && character == '"'
            break
          end
          escaped = !escaped && character == "\\"
          escaped = false if character != "\\" && escaped == false
          finish += 1
        end
        literal = source[index..finish]
        tokens << Token.new(:string, JSON.parse(literal))
        index = finish + 1
      when /[A-Za-z_]/
        finish = index + 1
        finish += 1 while finish < source.length && source[finish] =~ /[A-Za-z0-9_]/
        tokens << Token.new(:identifier, source[index...finish])
        index = finish
      when '(', ')', ',', '+'
        tokens << Token.new(source[index].to_sym, source[index])
        index += 1
      else
        index += 1
      end
    end
    tokens
  end

  def parse_map
    expect(:identifier, "d")
    expect(:'(')
    result = {}
    until peek&.kind == :')'
      key = expect(:string).value
      expect(:identifier, "to")
      result[key] = if peek.kind == :identifier && peek.value == "d"
                      parse_map
                    else
                      parse_concatenated_string
                    end
      consume(:',')
    end
    expect(:')')
    result
  end

  def parse_concatenated_string
    value = expect(:string).value
    while consume(:'+')
      value += expect(:string).value
    end
    value
  end

  def peek
    @tokens[@index]
  end

  def consume(kind)
    return false unless peek&.kind == kind
    @index += 1
    true
  end

  def expect(kind, value = nil)
    token = peek
    unless token&.kind == kind && (value.nil? || token.value == value)
      raise "Expected #{kind} #{value.inspect}, got #{token&.kind} #{token&.value.inspect} at token #{@index}"
    end
    @index += 1
    token
  end
end

def flatten(value, prefix = nil, destination = {})
  value.each do |key, child|
    path = [prefix, key].compact.join(".")
    child.is_a?(Hash) ? flatten(child, path, destination) : destination[path] = child
  end
  destination
end

def swift_literal(value)
  value.to_json
       .gsub("\\/", "/")
       .gsub("\\u2028", "\\u{2028}")
       .gsub("\\u2029", "\\u{2029}")
end

catalogs = LANGUAGES.to_h do |language|
  filename = File.join(SOURCE_DIR, "#{language.capitalize}.kt")
  [language, flatten(KotlinDictionaryParser.new(File.read(filename, encoding: "UTF-8")).parse)]
end

swift = String.new(<<~SWIFT)
  // Generated by ios/scripts/generate_localization_catalogs.rb. Do not edit manually.
  // Source of truth: kotlin/.../i18n/dictionaries/{Pt,En,Zh,Ms,Id,Tl}.kt
  import Foundation

SWIFT

catalogs.each do |language, entries|
  swift << "let generated#{language.capitalize}Strings: [String: String] = [\n"
  entries.sort.each do |key, value|
    swift << "    #{swift_literal(key)}: #{swift_literal(value)},\n"
  end
  swift << "]\n\n"
end

swift << <<~SWIFT
  let generatedLocalizationCatalogs: [String: [String: String]] = [
      "pt": generatedPtStrings,
      "en": generatedEnStrings,
      "zh": generatedZhStrings,
      "ms": generatedMsStrings,
      "id": generatedIdStrings,
      "tl": generatedTlStrings,
  ]
SWIFT

File.write(OUTPUT, swift, mode: "w", encoding: "UTF-8")
warn "Generated #{OUTPUT} (#{catalogs.transform_values(&:size)})"
